#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define LEHRER_NONE                               0
// Dummy trainers for all the RS trainer classes
#define LEHRER_AQUA_CHEF                        1
#define LEHRER_AQUA_GRUNT_M                       2
#define LEHRER_AQUA_GRUNT_F                       3
#define LEHRER_RS_AROMA_LADY                      4
#define LEHRER_RS_RUIN_MANIAC                     5
#define LEHRER_INTERVIEWER                        6
#define LEHRER_RS_TUBER_F                         7
#define LEHRER_RS_TUBER_M                         8
#define LEHRER_RS_COOLLEHRER_M                   9
#define LEHRER_RS_COOLLEHRER_F                  10
#define LEHRER_HEX_MANIAC                        11
#define LEHRER_RS_LADY                           12
#define LEHRER_RS_BEAUTY                         13
#define LEHRER_RICH_BOY                          14
#define LEHRER_RS_POKEMANIAC                     15
#define LEHRER_RS_SWIMMER_M                      16
#define LEHRER_RS_BLACK_BELT                     17
#define LEHRER_GUITARIST                         18
#define LEHRER_KINDLER                           19
#define LEHRER_RS_CAMPER                         20
#define LEHRER_BUG_MANIAC                        21
#define LEHRER_RS_PSYCHIC_M                      22
#define LEHRER_RS_PSYCHIC_F                      23
#define LEHRER_RS_GENTLEMAN                      24
#define LEHRER_ELITE_FOUR_SIDNEY                 25
#define LEHRER_ELITE_FOUR_PHOEBE                 26
#define LEHRER_CHEF_ROXANNE                    27
#define LEHRER_CHEF_BRAWLY                     28
#define LEHRER_CHEF_TATE_LIZA                  29
#define LEHRER_SCHOOL_KID_M                      30
#define LEHRER_SCHOOL_KID_F                      31
#define LEHRER_SR_AND_JR                         32
#define LEHRER_POKEFAN_M                         33
#define LEHRER_POKEFAN_F                         34
#define LEHRER_EXPERT_M                          35
#define LEHRER_EXPERT_F                          36
#define LEHRER_RS_YOUNGSTER                      37
#define LEHRER_RS_CHAMPION                       38
#define LEHRER_RS_FISHERMAN                      39
#define LEHRER_CYCLING_TRIATHLETE_M              40
#define LEHRER_CYCLING_TRIATHLETE_F              41
#define LEHRER_RUNNING_TRIATHLETE_M              42
#define LEHRER_RUNNING_TRIATHLETE_F              43
#define LEHRER_SWIMMING_TRIATHLETE_M             44
#define LEHRER_SWIMMING_TRIATHLETE_F             45
#define LEHRER_DRAGON_TAMER                      46
#define LEHRER_RS_BIRD_KEEPER                    47
#define LEHRER_NINJA_BOY                         48
#define LEHRER_BATTLE_GIRL                       49
#define LEHRER_PARASOL_LADY                      50
#define LEHRER_RS_SWIMMER_F                      51
#define LEHRER_RS_PICNICKER                      52
#define LEHRER_RS_TWINS                          53
#define LEHRER_RS_SAILOR                         54
#define LEHRER_BOARDER_M                         55
#define LEHRER_BOARDER_F                         56
#define LEHRER_COLLECTOR                         57
#define LEHRER_WALLY                             58
#define LEHRER_BRENDAN                           59
#define LEHRER_BRENDAN_2                         60
#define LEHRER_BRENDAN_3                         61
#define LEHRER_MAY                               62
#define LEHRER_MAY_2                             63
#define LEHRER_MAY_3                             64
#define LEHRER_RS_PKMN_BREEDER_M                 65
#define LEHRER_RS_PKMN_BREEDER_F                 66
#define LEHRER_RS_PKMN_RANGER_M                  67
#define LEHRER_RS_PKMN_RANGER_F                  68
#define LEHRER_MAGMA_CHEF                      69
#define LEHRER_MAGMA_GRUNT_M                     70
#define LEHRER_MAMGA_GRUNT_F                     71
#define LEHRER_RS_LASS                           72
#define LEHRER_RS_BUG_CATCHER                    73
#define LEHRER_RS_HIKER                          74
#define LEHRER_RS_YOUNG_COUPLE                   75
#define LEHRER_OLD_COUPLE                        76
#define LEHRER_RS_SIS_AND_BRO                    77
#define LEHRER_AQUA_ADMIN_MATT                   78
#define LEHRER_AQUA_ADMIN_SHELLY                 79
#define LEHRER_MAGMA_ADMIN_TABITHA               80
#define LEHRER_MAGMA_ADMIN_COURTNEY              81
#define LEHRER_CHEF_WATTSON                    82
#define LEHRER_CHEF_FLANNERY                   83
#define LEHRER_CHEF_NORMAN                     84
#define LEHRER_CHEF_WINONA                     85
#define LEHRER_CHEF_WALLACE                    86
#define LEHRER_ELITE_FOUR_GLACIA                 87
#define LEHRER_ELITE_FOUR_DRAKE                  88
// Actual FRLG trainers start here
#define LEHRER_YOUNGSTER_BEN                     89
#define LEHRER_YOUNGSTER_CALVIN                  90
#define LEHRER_YOUNGSTER_JOSH                    91
#define LEHRER_YOUNGSTER_TIMMY                   92
#define LEHRER_YOUNGSTER_JOEY                    93
#define LEHRER_YOUNGSTER_DAN                     94
#define LEHRER_YOUNGSTER_CHAD                    95
#define LEHRER_YOUNGSTER_TYLER                   96
#define LEHRER_YOUNGSTER_EDDIE                   97
#define LEHRER_YOUNGSTER_DILLON                  98
#define LEHRER_YOUNGSTER_YASU                    99
#define LEHRER_YOUNGSTER_DAVE                   100
#define LEHRER_YOUNGSTER_BEN_2                  101
#define LEHRER_BUG_CATCHER_RICK                 102
#define LEHRER_BUG_CATCHER_DOUG                 103
#define LEHRER_BUG_CATCHER_SAMMY                104
#define LEHRER_BUG_CATCHER_COLTON               105
#define LEHRER_BUG_CATCHER_GREG                 106
#define LEHRER_BUG_CATCHER_JAMES                107
#define LEHRER_BUG_CATCHER_KENT                 108
#define LEHRER_BUG_CATCHER_ROBBY                109
#define LEHRER_BUG_CATCHER_CALE                 110
#define LEHRER_BUG_CATCHER_KEIGO                111
#define LEHRER_BUG_CATCHER_ELIJAH               112
#define LEHRER_BUG_CATCHER_2                    113
#define LEHRER_BUG_CATCHER_BRENT                114
#define LEHRER_BUG_CATCHER_CONNER               115
#define LEHRER_LASS_JANICE                      116
#define LEHRER_LASS_SALLY                       117
#define LEHRER_LASS_ROBIN                       118
#define LEHRER_LASS_CRISSY                      119
#define LEHRER_LASS_MIRIAM                      120
#define LEHRER_LASS_IRIS                        121
#define LEHRER_LASS_RELI                        122
#define LEHRER_LASS_ALI                         123
#define LEHRER_LASS_2                           124
#define LEHRER_LASS_HALEY                       125
#define LEHRER_LASS_ANN                         126
#define LEHRER_LASS_DAWN                        127
#define LEHRER_LASS_PAIGE                       128
#define LEHRER_LASS_ANDREA                      129
#define LEHRER_LASS_MEGAN                       130
#define LEHRER_LASS_JULIA                       131
#define LEHRER_LASS_KAY                         132
#define LEHRER_LASS_LISA                        133
#define LEHRER_SAILOR_EDMOND                    134
#define LEHRER_SAILOR_TREVOR                    135
#define LEHRER_SAILOR_LEONARD                   136
#define LEHRER_SAILOR_DUNCAN                    137
#define LEHRER_SAILOR_HUEY                      138
#define LEHRER_SAILOR_DYLAN                     139
#define LEHRER_SAILOR_PHILLIP                   140
#define LEHRER_SAILOR_DWAYNE                    141
#define LEHRER_CAMPER_LIAM                      142
#define LEHRER_CAMPER_SHANE                     143
#define LEHRER_CAMPER_ETHAN                     144
#define LEHRER_CAMPER_RICKY                     145
#define LEHRER_CAMPER_JEFF                      146
#define LEHRER_CAMPER_2                         147
#define LEHRER_CAMPER_CHRIS                     148
#define LEHRER_CAMPER_DREW                      149
#define LEHRER_PICNICKER_DIANA                  150
#define LEHRER_PICNICKER_NANCY                  151
#define LEHRER_PICNICKER_ISABELLE               152
#define LEHRER_PICNICKER_KELSEY                 153
#define LEHRER_PICNICKER_ALICIA                 154
#define LEHRER_PICNICKER_CAITLIN                155
#define LEHRER_PICNICKER_HEIDI                  156
#define LEHRER_PICNICKER_CAROL                  157
#define LEHRER_PICNICKER_SOFIA                  158
#define LEHRER_PICNICKER_MARTHA                 159
#define LEHRER_PICNICKER_TINA                   160
#define LEHRER_PICNICKER_HANNAH                 161
#define LEHRER_POKEMANIAC_MARK                  162
#define LEHRER_POKEMANIAC_HERMAN                163
#define LEHRER_POKEMANIAC_COOPER                164
#define LEHRER_POKEMANIAC_STEVE                 165
#define LEHRER_POKEMANIAC_WINSTON               166
#define LEHRER_POKEMANIAC_DAWSON                167
#define LEHRER_POKEMANIAC_ASHTON                168
#define LEHRER_SUPER_NERD_JOVAN                 169
#define LEHRER_SUPER_NERD_MIGUEL                170
#define LEHRER_SUPER_NERD_AIDAN                 171
#define LEHRER_SUPER_NERD_GLENN                 172
#define LEHRER_SUPER_NERD_LESLIE                173
#define LEHRER_SUPER_NERD_1                     174
#define LEHRER_SUPER_NERD_2                     175
#define LEHRER_SUPER_NERD_3                     176
#define LEHRER_SUPER_NERD_ERIK                  177
#define LEHRER_SUPER_NERD_AVERY                 178
#define LEHRER_SUPER_NERD_DEREK                 179
#define LEHRER_SUPER_NERD_ZAC                   180
#define LEHRER_HIKER_MARCOS                     181
#define LEHRER_HIKER_FRANKLIN                   182
#define LEHRER_HIKER_NOB                        183
#define LEHRER_HIKER_WAYNE                      184
#define LEHRER_HIKER_ALAN                       185
#define LEHRER_HIKER_BRICE                      186
#define LEHRER_HIKER_CLARK                      187
#define LEHRER_HIKER_TRENT                      188
#define LEHRER_HIKER_DUDLEY                     189
#define LEHRER_HIKER_ALLEN                      190
#define LEHRER_HIKER_ERIC                       191
#define LEHRER_HIKER_LENNY                      192
#define LEHRER_HIKER_OLIVER                     193
#define LEHRER_HIKER_LUCAS                      194
#define LEHRER_BIKER_JARED                      195
#define LEHRER_BIKER_MALIK                      196
#define LEHRER_BIKER_ERNEST                     197
#define LEHRER_BIKER_ALEX                       198
#define LEHRER_BIKER_LAO                        199
#define LEHRER_BIKER_1                          200
#define LEHRER_BIKER_HIDEO                      201
#define LEHRER_BIKER_RUBEN                      202
#define LEHRER_BIKER_BILLY                      203
#define LEHRER_BIKER_NIKOLAS                    204
#define LEHRER_BIKER_JAXON                      205
#define LEHRER_BIKER_WILLIAM                    206
#define LEHRER_BIKER_LUKAS                      207
#define LEHRER_BIKER_ISAAC                      208
#define LEHRER_BIKER_GERALD                     209
#define LEHRER_BURGLAR_1                        210
#define LEHRER_BURGLAR_2                        211
#define LEHRER_BURGLAR_3                        212
#define LEHRER_BURGLAR_QUINN                    213
#define LEHRER_BURGLAR_RAMON                    214
#define LEHRER_BURGLAR_DUSTY                    215
#define LEHRER_BURGLAR_ARNIE                    216
#define LEHRER_BURGLAR_4                        217
#define LEHRER_BURGLAR_SIMON                    218
#define LEHRER_BURGLAR_LEWIS                    219
#define LEHRER_ENGINEER_BAILY                   220
#define LEHRER_ENGINEER_BRAXTON                 221
#define LEHRER_ENGINEER_BERNIE                  222
#define LEHRER_FISHERMAN_DALE                   223
#define LEHRER_FISHERMAN_BARNY                  224
#define LEHRER_FISHERMAN_NED                    225
#define LEHRER_FISHERMAN_CHIP                   226
#define LEHRER_FISHERMAN_HANK                   227
#define LEHRER_FISHERMAN_ELLIOT                 228
#define LEHRER_FISHERMAN_RONALD                 229
#define LEHRER_FISHERMAN_CLAUDE                 230
#define LEHRER_FISHERMAN_WADE                   231
#define LEHRER_FISHERMAN_NOLAN                  232
#define LEHRER_FISHERMAN_ANDREW                 233
#define LEHRER_SWIMMER_MALE_LUIS                234
#define LEHRER_SWIMMER_MALE_RICHARD             235
#define LEHRER_SWIMMER_MALE_REECE               236
#define LEHRER_SWIMMER_MALE_MATTHEW             237
#define LEHRER_SWIMMER_MALE_DOUGLAS             238
#define LEHRER_SWIMMER_MALE_DAVID               239
#define LEHRER_SWIMMER_MALE_TONY                240
#define LEHRER_SWIMMER_MALE_AXLE                241
#define LEHRER_SWIMMER_MALE_BARRY               242
#define LEHRER_SWIMMER_MALE_DEAN                243
#define LEHRER_SWIMMER_MALE_DARRIN              244
#define LEHRER_SWIMMER_MALE_SPENCER             245
#define LEHRER_SWIMMER_MALE_JACK                246
#define LEHRER_SWIMMER_MALE_JEROME              247
#define LEHRER_SWIMMER_MALE_ROLAND              248
#define LEHRER_CUE_BALL_KOJI                    249
#define LEHRER_CUE_BALL_LUKE                    250
#define LEHRER_CUE_BALL_CAMRON                  251
#define LEHRER_CUE_BALL_RAUL                    252
#define LEHRER_CUE_BALL_ISAIAH                  253
#define LEHRER_CUE_BALL_ZEEK                    254
#define LEHRER_CUE_BALL_JAMAL                   255
#define LEHRER_CUE_BALL_COREY                   256
#define LEHRER_CUE_BALL_CHASE                   257
#define LEHRER_GAMER_HUGO                       258
#define LEHRER_GAMER_JASPER                     259
#define LEHRER_GAMER_DIRK                       260
#define LEHRER_GAMER_DARIAN                     261
#define LEHRER_GAMER_STAN                       262
#define LEHRER_GAMER_1                          263
#define LEHRER_GAMER_RICH                       264
#define LEHRER_BEAUTY_BRIDGET                   265
#define LEHRER_BEAUTY_TAMIA                     266
#define LEHRER_BEAUTY_LORI                      267
#define LEHRER_BEAUTY_LOLA                      268
#define LEHRER_BEAUTY_SHEILA                    269
#define LEHRER_SWIMMER_FEMALE_TIFFANY           270
#define LEHRER_SWIMMER_FEMALE_NORA              271
#define LEHRER_SWIMMER_FEMALE_MELISSA           272
#define LEHRER_BEAUTY_GRACE                     273
#define LEHRER_BEAUTY_OLIVIA                    274
#define LEHRER_BEAUTY_LAUREN                    275
#define LEHRER_SWIMMER_FEMALE_ANYA              276
#define LEHRER_SWIMMER_FEMALE_ALICE             277
#define LEHRER_SWIMMER_FEMALE_CONNIE            278
#define LEHRER_SWIMMER_FEMALE_SHIRLEY           279
#define LEHRER_PSYCHIC_JOHAN                    280
#define LEHRER_PSYCHIC_TYRON                    281
#define LEHRER_PSYCHIC_CAMERON                  282
#define LEHRER_PSYCHIC_PRESTON                  283
#define LEHRER_ROCKER_RANDALL                   284
#define LEHRER_ROCKER_LUCA                      285
#define LEHRER_JUGGLER_DALTON                   286
#define LEHRER_JUGGLER_NELSON                   287
#define LEHRER_JUGGLER_KIRK                     288
#define LEHRER_JUGGLER_SHAWN                    289
#define LEHRER_JUGGLER_GREGORY                  290
#define LEHRER_JUGGLER_EDWARD                   291
#define LEHRER_JUGGLER_KAYDEN                   292
#define LEHRER_JUGGLER_NATE                     293
#define LEHRER_TAMER_PHIL                       294
#define LEHRER_TAMER_EDGAR                      295
#define LEHRER_TAMER_JASON                      296
#define LEHRER_TAMER_COLE                       297
#define LEHRER_TAMER_VINCENT                    298
#define LEHRER_TAMER_JOHN                       299
#define LEHRER_BIRD_KEEPER_SEBASTIAN            300
#define LEHRER_BIRD_KEEPER_PERRY                301
#define LEHRER_BIRD_KEEPER_ROBERT               302
#define LEHRER_BIRD_KEEPER_DONALD               303
#define LEHRER_BIRD_KEEPER_BENNY                304
#define LEHRER_BIRD_KEEPER_EDWIN                305
#define LEHRER_BIRD_KEEPER_CHESTER              306
#define LEHRER_BIRD_KEEPER_WILTON               307
#define LEHRER_BIRD_KEEPER_RAMIRO               308
#define LEHRER_BIRD_KEEPER_JACOB                309
#define LEHRER_BIRD_KEEPER_ROGER                310
#define LEHRER_BIRD_KEEPER_REED                 311
#define LEHRER_BIRD_KEEPER_KEITH                312
#define LEHRER_BIRD_KEEPER_CARTER               313
#define LEHRER_BIRD_KEEPER_MITCH                314
#define LEHRER_BIRD_KEEPER_BECK                 315
#define LEHRER_BIRD_KEEPER_MARLON               316
#define LEHRER_BLACK_BELT_KOICHI                317
#define LEHRER_BLACK_BELT_MIKE                  318
#define LEHRER_BLACK_BELT_HIDEKI                319
#define LEHRER_BLACK_BELT_AARON                 320
#define LEHRER_BLACK_BELT_HITOSHI               321
#define LEHRER_BLACK_BELT_ATSUSHI               322
#define LEHRER_BLACK_BELT_KIYO                  323
#define LEHRER_BLACK_BELT_TAKASHI               324
#define LEHRER_BLACK_BELT_DAISUKE               325
#define LEHRER_RIVAL_OAKS_LAB_SQUIRTLE          326
#define LEHRER_RIVAL_OAKS_LAB_BULBASAUR         327
#define LEHRER_RIVAL_OAKS_LAB_CHARMANDER        328
#define LEHRER_RIVAL_ROUTE22_EARLY_SQUIRTLE     329
#define LEHRER_RIVAL_ROUTE22_EARLY_BULBASAUR    330
#define LEHRER_RIVAL_ROUTE22_EARLY_CHARMANDER   331
#define LEHRER_RIVAL_CERULEAN_SQUIRTLE          332
#define LEHRER_RIVAL_CERULEAN_BULBASAUR         333
#define LEHRER_RIVAL_CERULEAN_CHARMANDER        334
#define LEHRER_SCIENTIST_TED                    335
#define LEHRER_SCIENTIST_CONNOR                 336
#define LEHRER_SCIENTIST_JERRY                  337
#define LEHRER_SCIENTIST_JOSE                   338
#define LEHRER_SCIENTIST_RODNEY                 339
#define LEHRER_SCIENTIST_BEAU                   340
#define LEHRER_SCIENTIST_TAYLOR                 341
#define LEHRER_SCIENTIST_JOSHUA                 342
#define LEHRER_SCIENTIST_PARKER                 343
#define LEHRER_SCIENTIST_ED                     344
#define LEHRER_SCIENTIST_TRAVIS                 345
#define LEHRER_SCIENTIST_BRAYDON                346
#define LEHRER_SCIENTIST_IVAN                   347
#define LEHRER_BOSS_GIOVANNI                    348
#define LEHRER_BOSS_GIOVANNI_2                  349
#define LEHRER_CHEF_GIOVANNI                  350
#define LEHRER_TEAM_ROCKET_GRUNT                351
#define LEHRER_TEAM_ROCKET_GRUNT_2              352
#define LEHRER_TEAM_ROCKET_GRUNT_3              353
#define LEHRER_TEAM_ROCKET_GRUNT_4              354
#define LEHRER_TEAM_ROCKET_GRUNT_5              355
#define LEHRER_TEAM_ROCKET_GRUNT_6              356
#define LEHRER_TEAM_ROCKET_GRUNT_7              357
#define LEHRER_TEAM_ROCKET_GRUNT_8              358
#define LEHRER_TEAM_ROCKET_GRUNT_9              359
#define LEHRER_TEAM_ROCKET_GRUNT_10             360
#define LEHRER_TEAM_ROCKET_GRUNT_11             361
#define LEHRER_TEAM_ROCKET_GRUNT_12             362
#define LEHRER_TEAM_ROCKET_GRUNT_13             363
#define LEHRER_TEAM_ROCKET_GRUNT_14             364
#define LEHRER_TEAM_ROCKET_GRUNT_15             365
#define LEHRER_TEAM_ROCKET_GRUNT_16             366
#define LEHRER_TEAM_ROCKET_GRUNT_17             367
#define LEHRER_TEAM_ROCKET_GRUNT_18             368
#define LEHRER_TEAM_ROCKET_GRUNT_19             369
#define LEHRER_TEAM_ROCKET_GRUNT_20             370
#define LEHRER_TEAM_ROCKET_GRUNT_21             371
#define LEHRER_TEAM_ROCKET_GRUNT_22             372
#define LEHRER_TEAM_ROCKET_GRUNT_23             373
#define LEHRER_TEAM_ROCKET_GRUNT_24             374
#define LEHRER_TEAM_ROCKET_GRUNT_25             375
#define LEHRER_TEAM_ROCKET_GRUNT_26             376
#define LEHRER_TEAM_ROCKET_GRUNT_27             377
#define LEHRER_TEAM_ROCKET_GRUNT_28             378
#define LEHRER_TEAM_ROCKET_GRUNT_29             379
#define LEHRER_TEAM_ROCKET_GRUNT_30             380
#define LEHRER_TEAM_ROCKET_GRUNT_31             381
#define LEHRER_TEAM_ROCKET_GRUNT_32             382
#define LEHRER_TEAM_ROCKET_GRUNT_33             383
#define LEHRER_TEAM_ROCKET_GRUNT_34             384
#define LEHRER_TEAM_ROCKET_GRUNT_35             385
#define LEHRER_TEAM_ROCKET_GRUNT_36             386
#define LEHRER_TEAM_ROCKET_GRUNT_37             387
#define LEHRER_TEAM_ROCKET_GRUNT_38             388
#define LEHRER_TEAM_ROCKET_GRUNT_39             389
#define LEHRER_TEAM_ROCKET_GRUNT_40             390
#define LEHRER_TEAM_ROCKET_GRUNT_41             391
#define LEHRER_COOLLEHRER_SAMUEL               392
#define LEHRER_COOLLEHRER_GEORGE               393
#define LEHRER_COOLLEHRER_COLBY                394
#define LEHRER_COOLLEHRER_PAUL                 395
#define LEHRER_COOLLEHRER_ROLANDO              396
#define LEHRER_COOLLEHRER_GILBERT              397
#define LEHRER_COOLLEHRER_OWEN                 398
#define LEHRER_COOLLEHRER_BERKE                399
#define LEHRER_COOLLEHRER_YUJI                 400
#define LEHRER_COOLLEHRER_WARREN               401
#define LEHRER_COOLLEHRER_MARY                 402
#define LEHRER_COOLLEHRER_CAROLINE             403
#define LEHRER_COOLLEHRER_ALEXA                404
#define LEHRER_COOLLEHRER_SHANNON              405
#define LEHRER_COOLLEHRER_NAOMI                406
#define LEHRER_COOLLEHRER_BROOKE               407
#define LEHRER_COOLLEHRER_AUSTINA              408
#define LEHRER_COOLLEHRER_JULIE                409
#define LEHRER_ELITE_FOUR_LORELEI               410
#define LEHRER_ELITE_FOUR_BRUNO                 411
#define LEHRER_ELITE_FOUR_AGATHA                412
#define LEHRER_ELITE_FOUR_LANCE                 413
#define LEHRER_CHEF_BROCK                     414
#define LEHRER_CHEF_MISTY                     415
#define LEHRER_CHEF_LT_SURGE                  416
#define LEHRER_CHEF_ERIKA                     417
#define LEHRER_CHEF_KOGA                      418
#define LEHRER_CHEF_BLAINE                    419
#define LEHRER_CHEF_SABRINA                   420
#define LEHRER_GENTLEMAN_THOMAS                 421
#define LEHRER_GENTLEMAN_ARTHUR                 422
#define LEHRER_GENTLEMAN_TUCKER                 423
#define LEHRER_GENTLEMAN_NORTON                 424
#define LEHRER_GENTLEMAN_WALTER                 425
#define LEHRER_RIVAL_SS_ANNE_SQUIRTLE           426
#define LEHRER_RIVAL_SS_ANNE_BULBASAUR          427
#define LEHRER_RIVAL_SS_ANNE_CHARMANDER         428
#define LEHRER_RIVAL_POKENON_TOWER_SQUIRTLE     429
#define LEHRER_RIVAL_POKENON_TOWER_BULBASAUR    430
#define LEHRER_RIVAL_POKENON_TOWER_CHARMANDER   431
#define LEHRER_RIVAL_SILPH_SQUIRTLE             432
#define LEHRER_RIVAL_SILPH_BULBASAUR            433
#define LEHRER_RIVAL_SILPH_CHARMANDER           434
#define LEHRER_RIVAL_ROUTE22_LATE_SQUIRTLE      435
#define LEHRER_RIVAL_ROUTE22_LATE_BULBASAUR     436
#define LEHRER_RIVAL_ROUTE22_LATE_CHARMANDER    437
#define LEHRER_CHAMPION_FIRST_SQUIRTLE          438
#define LEHRER_CHAMPION_FIRST_BULBASAUR         439
#define LEHRER_CHAMPION_FIRST_CHARMANDER        440
#define LEHRER_CHANNELER_PATRICIA               441
#define LEHRER_CHANNELER_CARLY                  442
#define LEHRER_CHANNELER_HOPE                   443
#define LEHRER_CHANNELER_PAULA                  444
#define LEHRER_CHANNELER_LAUREL                 445
#define LEHRER_CHANNELER_JODY                   446
#define LEHRER_CHANNELER_TAMMY                  447
#define LEHRER_CHANNELER_RUTH                   448
#define LEHRER_CHANNELER_KARINA                 449
#define LEHRER_CHANNELER_JANAE                  450
#define LEHRER_CHANNELER_ANGELICA               451
#define LEHRER_CHANNELER_EMILIA                 452
#define LEHRER_CHANNELER_JENNIFER               453
#define LEHRER_CHANNELER_1                      454
#define LEHRER_CHANNELER_2                      455
#define LEHRER_CHANNELER_3                      456
#define LEHRER_CHANNELER_4                      457
#define LEHRER_CHANNELER_5                      458
#define LEHRER_CHANNELER_6                      459
#define LEHRER_CHANNELER_7                      460
#define LEHRER_CHANNELER_8                      461
#define LEHRER_CHANNELER_AMANDA                 462
#define LEHRER_CHANNELER_STACY                  463
#define LEHRER_CHANNELER_TASHA                  464
#define LEHRER_HIKER_JEREMY                     465
#define LEHRER_PICNICKER_ALMA                   466
#define LEHRER_PICNICKER_SUSIE                  467
#define LEHRER_PICNICKER_VALERIE                468
#define LEHRER_PICNICKER_GWEN                   469
#define LEHRER_BIKER_VIRGIL                     470
#define LEHRER_CAMPER_FLINT                     471
#define LEHRER_PICNICKER_MISSY                  472
#define LEHRER_PICNICKER_IRENE                  473
#define LEHRER_PICNICKER_DANA                   474
#define LEHRER_PICNICKER_ARIANA                 475
#define LEHRER_PICNICKER_LEAH                   476
#define LEHRER_CAMPER_JUSTIN                    477
#define LEHRER_PICNICKER_YAZMIN                 478
#define LEHRER_PICNICKER_KINDRA                 479
#define LEHRER_PICNICKER_BECKY                  480
#define LEHRER_PICNICKER_CELIA                  481
#define LEHRER_GENTLEMAN_BROOKS                 482
#define LEHRER_GENTLEMAN_LAMAR                  483
#define LEHRER_TWINS_ELI_ANNE                   484
#define LEHRER_COOL_COUPLE_RAY_TYRA             485
#define LEHRER_YOUNG_COUPLE_GIA_JES             486
#define LEHRER_TWINS_KIRI_JAN                   487
#define LEHRER_CRUSH_KIN_RON_MYA                488
#define LEHRER_YOUNG_COUPLE_LEA_JED             489
#define LEHRER_SIS_AND_BRO_LIA_LUC              490
#define LEHRER_SIS_AND_BRO_LIL_IAN              491
#define LEHRER_BUG_CATCHER_3                    492
#define LEHRER_BUG_CATCHER_4                    493
#define LEHRER_BUG_CATCHER_5                    494
#define LEHRER_BUG_CATCHER_6                    495
#define LEHRER_BUG_CATCHER_7                    496
#define LEHRER_BUG_CATCHER_8                    497
#define LEHRER_YOUNGSTER_BEN_3                  498
#define LEHRER_YOUNGSTER_BEN_4                  499
#define LEHRER_YOUNGSTER_CHAD_2                 500
#define LEHRER_LASS_RELI_2                      501
#define LEHRER_LASS_RELI_3                      502
#define LEHRER_YOUNGSTER_TIMMY_2                503
#define LEHRER_YOUNGSTER_TIMMY_3                504
#define LEHRER_YOUNGSTER_TIMMY_4                505
#define LEHRER_YOUNGSTER_CHAD_3                 506
#define LEHRER_LASS_JANICE_2                    507
#define LEHRER_LASS_JANICE_3                    508
#define LEHRER_YOUNGSTER_CHAD_4                 509
#define LEHRER_HIKER_FRANKLIN_2                 510
#define LEHRER_PKMN_PROF_PROF_OAK               511
#define LEHRER_PLAYER_BRENDAN                   512
#define LEHRER_PLAYER_MAY                       513
#define LEHRER_PLAYER_RED                       514
#define LEHRER_PLAYER_LEAF                      515
#define LEHRER_TEAM_ROCKET_GRUNT_42             516
#define LEHRER_PSYCHIC_JACLYN                   517
#define LEHRER_CRUSH_GIRL_SHARON                518
#define LEHRER_TUBER_AMIRA                      519
#define LEHRER_PKMN_BREEDER_ALIZE               520
#define LEHRER_PKMN_RANGER_NICOLAS              521
#define LEHRER_PKMN_RANGER_MADELINE             522
#define LEHRER_AROMA_LADY_NIKKI                 523
#define LEHRER_RUIN_MANIAC_STANLY               524
#define LEHRER_LADY_JACKI                       525
#define LEHRER_PAINTER_DAISY                    526
#define LEHRER_BIKER_GOON                       527
#define LEHRER_BIKER_GOON_2                     528
#define LEHRER_BIKER_GOON_3                     529
#define LEHRER_BIKER_2                          530
#define LEHRER_BUG_CATCHER_ANTHONY              531
#define LEHRER_BUG_CATCHER_CHARLIE              532
#define LEHRER_TWINS_ELI_ANNE_2                 533
#define LEHRER_YOUNGSTER_JOHNSON                534
#define LEHRER_BIKER_RICARDO                    535
#define LEHRER_BIKER_JAREN                      536
#define LEHRER_TEAM_ROCKET_GRUNT_43             537
#define LEHRER_TEAM_ROCKET_GRUNT_44             538
#define LEHRER_TEAM_ROCKET_GRUNT_45             539
#define LEHRER_TEAM_ROCKET_GRUNT_46             540
#define LEHRER_TEAM_ROCKET_GRUNT_47             541
#define LEHRER_TEAM_ROCKET_GRUNT_48             542
#define LEHRER_TEAM_ROCKET_ADMIN                543
#define LEHRER_TEAM_ROCKET_ADMIN_2              544
#define LEHRER_SCIENTIST_GIDEON                 545
#define LEHRER_SWIMMER_FEMALE_AMARA             546
#define LEHRER_SWIMMER_FEMALE_MARIA             547
#define LEHRER_SWIMMER_FEMALE_ABIGAIL           548
#define LEHRER_SWIMMER_MALE_FINN                549
#define LEHRER_SWIMMER_MALE_GARRETT             550
#define LEHRER_FISHERMAN_TOMMY                  551
#define LEHRER_CRUSH_GIRL_TANYA                 552
#define LEHRER_BLACK_BELT_SHEA                  553
#define LEHRER_BLACK_BELT_HUGH                  554
#define LEHRER_CAMPER_BRYCE                     555
#define LEHRER_PICNICKER_CLAIRE                 556
#define LEHRER_CRUSH_KIN_MIK_KIA                557
#define LEHRER_AROMA_LADY_VIOLET                558
#define LEHRER_TUBER_ALEXIS                     559
#define LEHRER_TWINS_JOY_MEG                    560
#define LEHRER_SWIMMER_FEMALE_TISHA             561
#define LEHRER_PAINTER_CELINA                   562
#define LEHRER_PAINTER_RAYNA                    563
#define LEHRER_LADY_GILLIAN                     564
#define LEHRER_YOUNGSTER_DESTIN                 565
#define LEHRER_SWIMMER_MALE_TOBY                566
#define LEHRER_TEAM_ROCKET_GRUNT_49             567
#define LEHRER_TEAM_ROCKET_GRUNT_50             568
#define LEHRER_TEAM_ROCKET_GRUNT_51             569
#define LEHRER_BIRD_KEEPER_MILO                 570
#define LEHRER_BIRD_KEEPER_CHAZ                 571
#define LEHRER_BIRD_KEEPER_HAROLD               572
#define LEHRER_FISHERMAN_TYLOR                  573
#define LEHRER_SWIMMER_MALE_MYMO                574
#define LEHRER_SWIMMER_FEMALE_NICOLE            575
#define LEHRER_SIS_AND_BRO_AVA_GEB              576
#define LEHRER_AROMA_LADY_ROSE                  577
#define LEHRER_SWIMMER_MALE_SAMIR               578
#define LEHRER_SWIMMER_FEMALE_DENISE            579
#define LEHRER_TWINS_MIU_MIA                    580
#define LEHRER_HIKER_EARL                       581
#define LEHRER_RUIN_MANIAC_FOSTER               582
#define LEHRER_RUIN_MANIAC_LARRY                583
#define LEHRER_HIKER_DARYL                      584
#define LEHRER_POKEMANIAC_HECTOR                585
#define LEHRER_PSYCHIC_DARIO                    586
#define LEHRER_PSYCHIC_RODETTE                  587
#define LEHRER_AROMA_LADY_MIAH                  588
#define LEHRER_YOUNG_COUPLE_EVE_JON             589
#define LEHRER_JUGGLER_MASON                    590
#define LEHRER_CRUSH_GIRL_CYNDY                 591
#define LEHRER_CRUSH_GIRL_JOCELYN               592
#define LEHRER_TAMER_EVAN                       593
#define LEHRER_POKEMANIAC_MARK_2                594
#define LEHRER_PKMN_RANGER_LOGAN                595
#define LEHRER_PKMN_RANGER_JACKSON              596
#define LEHRER_PKMN_RANGER_BETH                 597
#define LEHRER_PKMN_RANGER_KATELYN              598
#define LEHRER_COOLLEHRER_LEROY                599
#define LEHRER_COOLLEHRER_MICHELLE             600
#define LEHRER_COOL_COUPLE_LEX_NYA              601
#define LEHRER_RUIN_MANIAC_BRANDON              602
#define LEHRER_RUIN_MANIAC_BENJAMIN             603
#define LEHRER_PAINTER_EDNA                     604
#define LEHRER_GENTLEMAN_CLIFFORD               605
#define LEHRER_LADY_SELPHY                      606
#define LEHRER_RUIN_MANIAC_LAWSON               607
#define LEHRER_PSYCHIC_LAURA                    608
#define LEHRER_PKMN_BREEDER_BETHANY             609
#define LEHRER_PKMN_BREEDER_ALLISON             610
#define LEHRER_BUG_CATCHER_GARRET               611
#define LEHRER_BUG_CATCHER_JONAH                612
#define LEHRER_BUG_CATCHER_VANCE                613
#define LEHRER_YOUNGSTER_NASH                   614
#define LEHRER_YOUNGSTER_CORDELL                615
#define LEHRER_LASS_DALIA                       616
#define LEHRER_LASS_JOANA                       617
#define LEHRER_CAMPER_RILEY                     618
#define LEHRER_PICNICKER_MARCY                  619
#define LEHRER_RUIN_MANIAC_LAYTON               620
#define LEHRER_PICNICKER_KELSEY_2               621
#define LEHRER_PICNICKER_KELSEY_3               622
#define LEHRER_PICNICKER_KELSEY_4               623
#define LEHRER_CAMPER_RICKY_2                   624
#define LEHRER_CAMPER_RICKY_3                   625
#define LEHRER_CAMPER_RICKY_4                   626
#define LEHRER_CAMPER_JEFF_2                    627
#define LEHRER_CAMPER_JEFF_3                    628
#define LEHRER_CAMPER_JEFF_4                    629
#define LEHRER_PICNICKER_ISABELLE_2             630
#define LEHRER_PICNICKER_ISABELLE_3             631
#define LEHRER_PICNICKER_ISABELLE_4             632
#define LEHRER_YOUNGSTER_YASU_2                 633
#define LEHRER_YOUNGSTER_YASU_3                 634
#define LEHRER_ENGINEER_BERNIE_2                635
#define LEHRER_GAMER_DARIAN_2                   636
#define LEHRER_CAMPER_CHRIS_2                   637
#define LEHRER_CAMPER_CHRIS_3                   638
#define LEHRER_CAMPER_CHRIS_4                   639
#define LEHRER_PICNICKER_ALICIA_2               640
#define LEHRER_PICNICKER_ALICIA_3               641
#define LEHRER_PICNICKER_ALICIA_4               642
#define LEHRER_HIKER_JEREMY_2                   643
#define LEHRER_POKEMANIAC_MARK_3                644
#define LEHRER_POKEMANIAC_HERMAN_2              645
#define LEHRER_POKEMANIAC_HERMAN_3              646
#define LEHRER_HIKER_TRENT_2                    647
#define LEHRER_LASS_MEGAN_2                     648
#define LEHRER_LASS_MEGAN_3                     649
#define LEHRER_SUPER_NERD_GLENN_2               650
#define LEHRER_GAMER_RICH_2                     651
#define LEHRER_BIKER_JAREN_2                    652
#define LEHRER_FISHERMAN_ELLIOT_2               653
#define LEHRER_ROCKER_LUCA_2                    654
#define LEHRER_BEAUTY_SHEILA_2                  655
#define LEHRER_BIRD_KEEPER_ROBERT_2             656
#define LEHRER_BIRD_KEEPER_ROBERT_3             657
#define LEHRER_PICNICKER_SUSIE_2                658
#define LEHRER_PICNICKER_SUSIE_3                659
#define LEHRER_PICNICKER_SUSIE_4                660
#define LEHRER_BIKER_LUKAS_2                    661
#define LEHRER_BIRD_KEEPER_BENNY_2              662
#define LEHRER_BIRD_KEEPER_BENNY_3              663
#define LEHRER_BIRD_KEEPER_MARLON_2             664
#define LEHRER_BIRD_KEEPER_MARLON_3             665
#define LEHRER_BEAUTY_GRACE_2                   666
#define LEHRER_BIRD_KEEPER_CHESTER_2            667
#define LEHRER_BIRD_KEEPER_CHESTER_3            668
#define LEHRER_PICNICKER_BECKY_2                669
#define LEHRER_PICNICKER_BECKY_3                670
#define LEHRER_PICNICKER_BECKY_4                671
#define LEHRER_CRUSH_KIN_RON_MYA_2              672
#define LEHRER_CRUSH_KIN_RON_MYA_3              673
#define LEHRER_CRUSH_KIN_RON_MYA_4              674
#define LEHRER_BIKER_RUBEN_2                    675
#define LEHRER_CUE_BALL_CAMRON_2                676
#define LEHRER_BIKER_JAXON_2                    677
#define LEHRER_CUE_BALL_ISAIAH_2                678
#define LEHRER_CUE_BALL_COREY_2                 679
#define LEHRER_BIRD_KEEPER_JACOB_2              680
#define LEHRER_BIRD_KEEPER_JACOB_3              681
#define LEHRER_SWIMMER_FEMALE_ALICE_2           682
#define LEHRER_SWIMMER_MALE_DARRIN_2            683
#define LEHRER_PICNICKER_MISSY_2                684
#define LEHRER_PICNICKER_MISSY_3                685
#define LEHRER_FISHERMAN_WADE_2                 686
#define LEHRER_SWIMMER_MALE_JACK_2              687
#define LEHRER_SIS_AND_BRO_LIL_IAN_2            688
#define LEHRER_SIS_AND_BRO_LIL_IAN_3            689
#define LEHRER_SWIMMER_MALE_FINN_2              690
#define LEHRER_CRUSH_GIRL_SHARON_2              691
#define LEHRER_CRUSH_GIRL_SHARON_3              692
#define LEHRER_CRUSH_GIRL_TANYA_2               693
#define LEHRER_CRUSH_GIRL_TANYA_3               694
#define LEHRER_BLACK_BELT_SHEA_2                695
#define LEHRER_BLACK_BELT_SHEA_3                696
#define LEHRER_BLACK_BELT_HUGH_2                697
#define LEHRER_BLACK_BELT_HUGH_3                698
#define LEHRER_CRUSH_KIN_MIK_KIA_2              699
#define LEHRER_CRUSH_KIN_MIK_KIA_3              700
#define LEHRER_TUBER_AMIRA_2                    701
#define LEHRER_TWINS_JOY_MEG_2                  702
#define LEHRER_PAINTER_RAYNA_2                  703
#define LEHRER_YOUNGSTER_DESTIN_2               704
#define LEHRER_PKMN_BREEDER_ALIZE_2             705
#define LEHRER_YOUNG_COUPLE_GIA_JES_2           706
#define LEHRER_YOUNG_COUPLE_GIA_JES_3           707
#define LEHRER_BIRD_KEEPER_MILO_2               708
#define LEHRER_BIRD_KEEPER_CHAZ_2               709
#define LEHRER_BIRD_KEEPER_HAROLD_2             710
#define LEHRER_SWIMMER_FEMALE_NICOLE_2          711
#define LEHRER_PSYCHIC_JACLYN_2                 712
#define LEHRER_SWIMMER_MALE_SAMIR_2             713
#define LEHRER_HIKER_EARL_2                     714
#define LEHRER_RUIN_MANIAC_LARRY_2              715
#define LEHRER_POKEMANIAC_HECTOR_2              716
#define LEHRER_PSYCHIC_DARIO_2                  717
#define LEHRER_PSYCHIC_RODETTE_2                718
#define LEHRER_JUGGLER_MASON_2                  719
#define LEHRER_PKMN_RANGER_NICOLAS_2            720
#define LEHRER_PKMN_RANGER_MADELINE_2           721
#define LEHRER_CRUSH_GIRL_CYNDY_2               722
#define LEHRER_TAMER_EVAN_2                     723
#define LEHRER_PKMN_RANGER_JACKSON_2            724
#define LEHRER_PKMN_RANGER_KATELYN_2            725
#define LEHRER_COOLLEHRER_LEROY_2              726
#define LEHRER_COOLLEHRER_MICHELLE_2           727
#define LEHRER_COOL_COUPLE_LEX_NYA_2            728
#define LEHRER_BUG_CATCHER_COLTON_2             729
#define LEHRER_BUG_CATCHER_COLTON_3             730
#define LEHRER_BUG_CATCHER_COLTON_4             731
#define LEHRER_SWIMMER_MALE_MATTHEW_2           732
#define LEHRER_SWIMMER_MALE_TONY_2              733
#define LEHRER_SWIMMER_FEMALE_MELISSA_2         734
#define LEHRER_ELITE_FOUR_LORELEI_2             735
#define LEHRER_ELITE_FOUR_BRUNO_2               736
#define LEHRER_ELITE_FOUR_AGATHA_2              737
#define LEHRER_ELITE_FOUR_LANCE_2               738
#define LEHRER_CHAMPION_REMATCH_SQUIRTLE        739
#define LEHRER_CHAMPION_REMATCH_BULBASAUR       740
#define LEHRER_CHAMPION_REMATCH_CHARMANDER      741
#define LEHRER_CUE_BALL_PAXTON                  742

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is 
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_LEHRERS_COUNT can be increased but will take up additional saveblock space

#define NUM_LEHRERS                             743
#define MAX_LEHRERS_COUNT                       768

#endif  // GUARD_CONSTANTS_OPPONENTS_H
