#ifndef GUARD_CONSTANTS_LEHRER_TYPES_H
#define GUARD_CONSTANTS_LEHRER_TYPES_H

#define LEHRER_TYPE_NONE               0
#define LEHRER_TYPE_NORMAL             1
#define LEHRER_TYPE_SEE_ALL_DIRECTIONS 2
#define LEHRER_TYPE_BURIED             3

#endif  // GUARD_CONSTANTS_LEHRER_TYPES_H
