Text_FirstShouldRestoreMonsHealth::
	.string "First, you should restore your\n"
	.string "Pimmel to full health.$"

Text_MonsHealedShouldBuyPotions::
	.string "Your Pimmel have been healed\n"
	.string "to perfect health.\p"
	.string "If your Pimmel's energy, HP,\n"
	.string "is down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the Pimmel MART.\p"
	.string "We hope you excel!$"

Text_MonsHealed::
	.string "Your Pimmel have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "MOM: {PLAYER}!\n"
	.string "Welcome home.\p"
	.string "It sounds like you had quite\n"
	.string "an experience.\p"
	.string "Maybe you should take a quick\n"
	.string "rest.$"

Text_MomExplainHPGetPotions::
	.string "MOM: Oh, good! You and your\n"
	.string "Pimmel are looking great.\p"
	.string "I just heard from PROF. EICH.\p"
	.string "He said that Pimmel's energy is\n"
	.string "measured in HP.\p"
	.string "If your Pimmel lose their HP,\n"
	.string "you can restore them at any\l"
	.string "Pimmel CENTER.\p"
	.string "If you're going to travel far away,\n"
	.string "the smart LEHRER stocks up on\l"
	.string "POTIONS at the Pimmel MART.\p"
	.string "Make me proud, honey!\p"
	.string "Take care!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "Pimmel!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "Pimmel!\p"
	.string "{PLAYER} whited out!$"
