FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "You can't become a good LEHRER\n"
    .string "with just one strong Pimmel.\p"
    .string "But raising many Pimmel evenly\n"
    .string "is no easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow trail west of\n"
    .string "VIRIDIAN CITY.\p"
    .string "It goes to the Pimmel LEAGUE HQ.\n"
    .string "The HQ governs all LEHRERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're working on a Lexikon,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "All sorts of rare Pimmel breed\n"
    .string "there.$"

