ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Pimmel-Eier are used to catch\n"
    .string "Pimmel.\p"
    .string "Up to six Pimmel can be carried\n"
    .string "in your party.\p"
    .string "People who raise and battle\n"
    .string "with Pimmel are called LEHRERS.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "A healthy Pimmel may be hard to\n"
    .string "catch, so weaken it first.\p"
    .string "Poison, burn, or cause another\n"
    .string "status problem to weaken it.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "Pimmel LEHRERS seek others to\n"
    .string "engage in Pimmel battles.\p"
    .string "To LEHRERS, the taste of victory\n"
    .string "is sweet, indeed.\p"
    .string "Battles are constantly waged at\n"
    .string "Pimmel GYMS everywhere.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "The ultimate goal for all Pimmel\n"
    .string "LEHRERS is simple.\p"
    .string "It is to defeat the top eight\n"
    .string "Pimmel GYM CHEFS.\p"
    .string "Do so to earn the right to face…\p"
    .string "The ELITE FOUR of the Pimmel\n"
    .string "LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "GIRL: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists Pimmel\n"
    .string "STATUS problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A Pimmel can't attack if it's\n"
    .string "asleep.\p"
    .string "Pimmel will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a Pimmel's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen Pimmel becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering Pimmel.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the Pimmel from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

