ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. EICH, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received EICH'S PARCEL\n"
    .string "from the Pimmel MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. EICH for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your Pimmel\n"
    .string "will need quick healing.$"

ViridianCity_Mart_Text_ReceivedHM01::
    .string "{PLAYER} received HM01\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM02::
    .string "{PLAYER} received HM02\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM03::
    .string "{PLAYER} received HM03\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM04::
    .string "{PLAYER} received HM04\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM05::
    .string "{PLAYER} received HM05\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM06::
    .string "{PLAYER} received HM06\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM07::
    .string "{PLAYER} received HM07\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_ReceivedHM08::
    .string "{PLAYER} received HM08\n"
    .string "from Schwuchtle.$"

ViridianCity_Mart_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"